import { useState } from "react";
import { Co, shadow, font } from "../theme.js";
import { m2t, tL } from "../utils.js";

export function Btn(p) {
var base = { padding: "14px 16px", borderRadius: 10, border: "none", cursor: "pointer", fontWeight: 600, fontSize: 15, ...font, transition: "all 0.1s" };
var v = p.variant || "default";
var s = v === "primary" ? { ...base, background: Co.ac, color: "#fff", boxShadow: "0 2px 8px " + Co.ac + "30" } : v === "generate" ? { ...base, background: Co.ac, color: "#fff", boxShadow: "0 2px 12px " + Co.ac + "40", letterSpacing: "0.02em" } : { ...base, background: Co.card, color: Co.txM, boxShadow: shadow.sm, border: "1px solid " + Co.bdr };
return <button aria-label={p["aria-label"]} style={{ ...s, opacity: p.disabled ? 0.5 : 1, ...p.style }} onClick={p.disabled ? null : p.onClick} disabled={p.disabled}>{p.children}</button>;
}
export function Inp(p) { return <input {...p} style={{ padding: "8px 10px", borderRadius: 6, border: "1px solid " + Co.bdr, background: Co.sf, fontSize: 13, ...font, color: Co.tx, outline: "none", width: "100%", boxSizing: "border-box", ...p.style }} />; }
export function Sel(p) { return <select value={p.value} onChange={function (e) { p.onChange(e.target.value); }} style={{ padding: "10px 28px 12px 10px", borderRadius: 6, border: "1px solid " + Co.bdr, background: Co.sf, fontSize: 13, ...font, color: Co.tx, outline: "none", width: "100%", boxSizing: "border-box", WebkitAppearance: "none", appearance: "none", lineHeight: 1.5, minHeight: 44, backgroundImage: "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='8' viewBox='0 0 12 8'%3E%3Cpath d='M1 1l5 5 5-5' stroke='%23999' stroke-width='1.5' fill='none'/%3E%3C/svg%3E\")", backgroundRepeat: "no-repeat", backgroundPosition: "right 8px center", ...p.style }}>{p.children}</select>; }
export function TSel(p) { var opts = []; for (var m = 0; m < 1440; m += 30) opts.push(m2t(m)); return <Sel value={p.value} onChange={p.onChange} style={{ width: 82, ...p.style }}>{opts.map(function (t) { return <option key={t} value={t}>{tL(t)}</option>; })}</Sel>; }
export function Tog(p) { var w = p.small ? 30 : 38, h = p.small ? 16 : 22, kn = p.small ? 12 : 18; return <div role="switch" aria-checked={!!p.value} aria-label={p["aria-label"]} tabIndex={p.disabled ? -1 : 0} onKeyDown={function (e) { if (!p.disabled && (e.key === "Enter" || e.key === " ")) { e.preventDefault(); p.onChange(!p.value); } }} onClick={function () { if (!p.disabled) p.onChange(!p.value); }} style={{ width: w, height: h, borderRadius: h/2, background: p.value ? (p.color || Co.ac) : Co.bdr, cursor: p.disabled ? "default" : "pointer", position: "relative", transition: "background 0.15s", flexShrink: 0, marginRight: p.small ? 4 : 0, outline: "none" }}><div style={{ width: kn, height: kn, borderRadius: kn/2, background: "#fff", position: "absolute", top: (h-kn)/2, left: p.value ? w-kn-2 : 2, transition: "left 0.15s", boxShadow: shadow.sm }} /></div>; }
export function NW(p) { return <div role="button" tabIndex={0} aria-label={p.value ? "Priority: Need (click to change to Want)" : "Priority: Want (click to change to Need)"} onKeyDown={function (e) { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); p.onChange(!p.value); } }} onClick={function () { p.onChange(!p.value); }} style={{ padding: "3px 10px", borderRadius: 4, fontSize: 11, fontWeight: 700, cursor: "pointer", background: p.value ? Co.rdS : Co.amS, color: p.value ? Co.rd : Co.am, textTransform: "uppercase", flexShrink: 0 }}>{p.value ? "Need" : "Want"}</div>; }
export function Card(p) { return <div style={{ background: Co.card, borderRadius: 12, boxShadow: shadow.md, padding: 20, marginBottom: 14, ...p.style }}>{p.children}</div>; }
export function SegBtn(p) { return <div role="button" tabIndex={0} aria-pressed={!!p.active} onKeyDown={function (e) { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); p.onClick(); } }} onClick={p.onClick} className="seg-control-option" style={{ background: p.active ? (p.color || Co.ac) : "transparent", color: p.active ? "#fff" : Co.txMu, borderLeft: p.borderLeft ? "1px solid " + Co.bdr : "none", ...p.style }}>{p.children}</div>; }
export function Collapsible(p) {
var [open, setOpen] = useState(p.defaultOpen || false);
function toggle() { setOpen(!open); }
return <Card style={p.style}><div role="button" tabIndex={0} aria-expanded={open} onKeyDown={function (e) { if (e.key === "Enter" || e.key === " ") { e.preventDefault(); toggle(); } }} onClick={toggle} style={{ display: "flex", alignItems: "center", cursor: "pointer" }}><div style={{ flex: 1 }}><div style={{ fontSize: 12, fontWeight: 700 }}>{p.title}</div>{open ? null : <div style={{ fontSize: 11, color: Co.txMu, marginTop: 1 }}>{p.summary}</div>}</div><span style={{ fontSize: 14, color: Co.txD, transform: open ? "rotate(90deg)" : "none", transition: "transform 0.15s" }}>{"\u203A"}</span></div>{open ? <div style={{ marginTop: 12, borderTop: "1px solid " + Co.bdrL, paddingTop: 12 }}>{p.children}</div> : null}</Card>;
}
